development:
  adapter: postgresql
  encoding: unicode
  database: blog_development
  pool: 5
  username: 
  password: 

test:
  adapter: postgresql
  encoding: unicode
  database: blog_test
  pool: 5
  username: 
  password: 
